contexts:
- data:
    output_dir: code-quarkus-redhat-processed
    services_dir: code-quarkus-redhat-services
    templates_dir: code-quarkus-redhat-templates
  name: code-quarkus-redhat
current: code-quarkus-redhat